cloud:
    aws:
        region:
            auto: false
            static: us-west-2
        credentials:
            accessKey: AKIAIOSFODNN7EXAMPLE
            secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            instanceProfile: false
