cloud:
    aws:
        region:
            auto: false
            static: us-west-2
        credentials:
            accessKey: AKIAJEKU7JJNPYL4TWMQ
            secretKey: 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
            instanceProfile: false